# Generated by Django 5.2.3 on 2026-09-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
