# Generated by Django 5.2.3 on 2026-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
