# Generated by Django 5.2.3 on 2026-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='artifacts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
