# Generated by Django 5.2.3 on 2026-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('quiet', 'Quiet')], default='blocked', max_length=10)),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('ssh', 'SSH')], default='auto', max_length=10)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('block_started_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-block_started_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', 'created_at'], name='security_lo_ip_515440_idx')],
            },
        ),
        migrations.CreateModel(
            name='SshEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('event_type', models.CharField(default='failed_password', max_length=50)),
                ('raw_line', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', 'created_at'], name='security_ss_ip_15a3d2_idx')],
            },
        ),
    ]
