# Generated by Django 5.2.3 on 2026-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('org', models.CharField(blank=True, default='', max_length=200)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
